CREATE TABLE
  music_albums (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    genre VARCHAR(255),
    label VARCHAR(255),
    publish_date DATE,
    archived BOOLEAN,
    genre_id INT,
    PRIMARY KEY (id),
    CONSTRAINT fk_genre_id FOREIGN KEY (genre_id) REFERENCES genres (id)
  );

CREATE TABLE
  genres (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    PRIMARY KEY (id)
  );