require_relative '../lib/Music/music_album'
require_relative '../lib/Music/genre'
require_relative '../lib/Game/game'
require_relative '../lib/Game/author'
require_relative '../lib/Book/book'
require_relative '../lib/Book/label'